version: '3.8'
services:
  database:
    restart: always
    image: postgres
    container_name: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - /tmp/github/workspace:/tmp/github/workspace
    env_file:
      - /tmp/github/workspace/.env
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=strapi
    healthcheck:
        test: ['CMD-SHELL', 'pg_isready', '-d', 'strapi']
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
    ports:
      - 5432:5432
  cms:
    restart: always
    image: ghcr.io/alsharp/cloud.blockberrypi.com/strapi-cms
    container_name: strapi-cms
    command: ['yarn', 'start']
    ports:
      - 1337:1337
    volumes:
      - /home/albert/strapi/public/uploads:/opt/app/public/uploads
      - /tmp/github/workspace:/tmp/github/workspace
    depends_on:
      - database
    env_file:
      - /tmp/github/workspace/.env
volumes:
  postgresdata: